name: ThirParAuth
version: 5.0
authors:
- LikeSauR
- HiScythe

main: com.likeitsmp.thirparauth.ThirparauthPlugin
api-version: 1.20

permissions:
    thirparauth.user:
        default: true

commands:
    3pa:
        aliases:
        - "3PA"
        - "thirparauth"
        - "threepah"
        permission: "thirparauth.user"
        description: "
            ยง1TODO: Description
            "
        usage: "
            ยง1TODO: Usage
            "